export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: "AUTH.INVALID_CREDENTIALS",
  ACCOUNT_LOCKED: "AUTH.ACCOUNT_LOCKED",
  ACCOUNT_DISABLED: "AUTH.ACCOUNT_DISABLED",
  EMAIL_NOT_VERIFIED: "AUTH.EMAIL_NOT_VERIFIED",
  ACCESS_TOKEN_EXPIRED: "AUTH.ACCESS_TOKEN_EXPIRED",
  REFRESH_TOKEN_EXPIRED: "AUTH.REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REUSED: "AUTH.REFRESH_TOKEN_REUSED",
  SESSION_REVOKED: "AUTH.SESSION_REVOKED",
  FORBIDDEN: "AUTH.FORBIDDEN",
} as const;
